#!/bin/bash


# save working directory
wd=(pwd)

TESTING=true


# define constants
ROOT_DIR=$(cat var/root_dir)
WEB_DIR=/var/www/wormbot


# handle installation directory
if [ "$#" -eq 1 ]
then
	ROOT_DIR=$1
	echo $ROOT_DIR > var/root_dir
elif [ "$#" -gt 1 ]
then
	echo "Usage: $0 [DIR]"
	exit
fi


# setup directories in root
sudo mkdir $ROOT_DIR
sudo mkdir $ROOT_DIR/experiments
sudo mkdir $WEB_DIR
sudo mkdir $WEB_DIR/experiments
sudo chmod a+r $WEB_DIR/experiments
sudo ln --symbolic -T $ROOT_DIR/experiments $WEB_DIR/experiments


# move necessary files to root dir
sudo cp camera.config platecoordinates.dat $ROOT_DIR


# move necessary files to web dir
sudo cp -r img $WEB_DIR


# move necessary files to cgi-bin
sudo cp bin/experimentbrowser bin/marker bin/scheduler /usr/lib/cgi-bin


# move script for wormbot in command-line
sudo cp bin/wormbot /bin

if [ $TESTING ]
then
	cp -r test_data/* $ROOT_DIR/experiments
fi
